### ISSUE TITLE
Class 'PhpParser\ParserFactory' not found

### ISSUE THREAD

**Issue by andreasciamanna** [exussum12/coverageChecker#52] opened 2019-03-15 10:37 UTC
Full error:

```
PHP Fatal error:  Class 'PhpParser\ParserFactory' not found in .../vendor/exussum12/coverage-checker/src/FileParser.php on line 21
PHP Stack trace:
PHP   1. {main}() .../vendor/exussum12/coverage-checker/bin/diffFilter:0
PHP   2. require() .../vendor/exussum12/coverage-checker/bin/diffFilter:3
PHP   3. exussum12\CoverageChecker\CoverageCheck->getCoveredLines() .../vendor/exussum12/coverage-checker/src/Runners/generic.php:76
PHP   4. exussum12\CoverageChecker\PhpCsLoader->parseLines() .../vendor/exussum12/coverage-checker/src/CoverageCheck.php:72
PHP   5. exussum12\CoverageChecker\PhpCsLoader->addInvalidLine() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:87
PHP   6. exussum12\CoverageChecker\PhpCsLoader->handleLookupError() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:130
PHP   7. exussum12\CoverageChecker\PhpCsLoader->getFileParser() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:166
PHP   8. exussum12\CoverageChecker\FileParser->__construct() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:184
```

I've found #33 which says the issue has been fixed in 0.9.0, but I'm running 0.11.0.

Here's the script I'm running locally (PHP 5.6.39: yes, I know):

```sh
CI_MERGE_REQUEST_TARGET_BRANCH_NAME=develop
FILES=$(git diff --name-only --diff-filter=ACMR HEAD origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} -- '*.php' '*.inc')
FILES=${FILES//$'\n'/ }

[[ -z "$FILES" ]] && { echo "Nothing to check": exit 0; }

echo "Checking ${FILES}"
echo "${FILES}" > ./files.txt

echo "Running checks..."
./vendor/bin/phpcs --standard=./phpcs.xml --report=json --file-list=files.txt > ./phpcs.json
echo "Parsing results..."

./vendor/bin/diffFilter --phpcs files.txt ./phpcs.json 100
```

Notice that I'm not using `./vendor/bin/phpcs --standard=./phpcs.xml --report=json --file-list=./files.txt || true > ./phpcs.json` because that generates an empty `phpcs.json`.

`CI_MERGE_REQUEST_TARGET_BRANCH_NAME` exists to make it easy for me to port the script in the CI.

With this script, I can see that both `files.txt` and `phpcs.json` are properly generated:
- `files.txt` contains the only PHP file changed from the source branch
- `phpcs.json` contains a good number data (not included here to not pollute the issue, but I can do it if that's needed) which is expected, as I intentionally used a file with a lot of legacy code, but made a one-line change.

I've spent a good time trying to figure out what the issue could be, but I couldn't.

Out of curiosity, I've tried the script in GitLab-CI, which runs on PHP 7.3.2:
```yaml
- composer install
- FILES=$(git diff --name-only --diff-filter=ACMR HEAD origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} -- '*.php' '*.inc')
- FILES=${FILES//$'\n'/ }
- '[[ -z "$FILES" ]] && { echo "Nothing to check": exit 0; }'
- echo "Checking ${FILES}"
- echo "${FILES}" > ./files.txt
- cat ./files.txt
- echo "Running checks..."
- ./vendor/bin/phpcs --standard=./phpcs.xml --report=json --file-list=./files.txt || true > ./phpcs.json
- cat ./phpcs.json
- echo "Parsing results..."
- ./vendor/bin/diffFilter --phpcs files.txt ./phpcs.json 100
```

Again, both files are properly generated, but on `./vendor/bin/diffFilter --phpcs files.txt ./phpcs.json 100` I get this generic error: `Can't Parse phpcs json - Syntax error`.

Full output:

```
$ FILES=$(git diff --name-only --diff-filter=ACMR HEAD origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} -- '*.php' '*.inc')
$ FILES=${FILES//$'\n'/ }
$ [[ -z "$FILES" ]] && { echo "Nothing to check": exit 0; }
$ echo "Checking ${FILES}"
Checking sitepress.php
$ echo "${FILES}" > ./files.txt
$ cat ./files.txt
sitepress.php
$ echo "Running checks..."
Running checks...
$ ./vendor/bin/phpcs --standard=./phpcs.xml --report=json --file-list=./files.txt || true > ./phpcs.json
{"totals":{"errors":39,"warnings":7,"fixable":12},"files":{"\/builds\/wpml\/sitepress-multilingual-cms\/sitepress.php":{"errors":39,"warnings":7,"messages":[{"message":"You must use \"\/**\" style comments for a file comment","source":"Squiz.Commenting.FileComment.WrongStyle","severity":5,"fixable":false,"type":"ERROR","line":2,"column":1},{"message":"Empty line required before block comment","source":"Squiz.Commenting.BlockComment.NoEmptyLineBefore","severity":5,"fixable":false,"type":"ERROR","line":2,"column":1},{"message":"No space found before comment text; expected \"\/\/ define('ICL_SITEPRESS_DEV_VERSION', '3.4-dev');\" but found \"\/\/define('ICL_SITEPRESS_DEV_VERSION', '3.4-dev');\"","source":"Squiz.Commenting.InlineComment.NoSpaceBefore","severity":5,"fixable":true,"type":"ERROR","line":25,"column":1},{"message":"Inline comments must end in full-stops, exclamation marks, or question marks","source":"Squiz.Commenting.InlineComment.InvalidEndChar","severity":5,"fixable":false,"type":"ERROR","line":25,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":31,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":33,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":35,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":37,"column":1},{"message":"No space found before comment text; expected \"\/\/ PHP 5.2 backward compatibility\" but found \"\/\/PHP 5.2 backward compatibility\"","source":"Squiz.Commenting.InlineComment.NoSpaceBefore","severity":5,"fixable":true,"type":"ERROR","line":40,"column":1},{"message":"Inline comments must end in full-stops, exclamation marks, or question marks","source":"Squiz.Commenting.InlineComment.InvalidEndChar","severity":5,"fixable":false,"type":"ERROR","line":40,"column":1},{"message":"Variable \"WPML_Dependencies\" is not in valid snake_case format","source":"WordPress.NamingConventions.ValidVariableName.NotSnakeCase","severity":5,"fixable":false,"type":"ERROR","line":54,"column":1},{"message":"\"require_once\" is a statement not a function; no parentheses are required","source":"PEAR.Files.IncludingFile.BracketsNotRequired","severity":5,"fixable":true,"type":"WARNING","line":97,"column":1},{"message":"Inline comments must end in full-stops, exclamation marks, or question marks","source":"Squiz.Commenting.InlineComment.InvalidEndChar","severity":5,"fixable":false,"type":"ERROR","line":120,"column":1},{"message":"No space found before comment text; expected \"\/\/ Set cron job to update WPML config index file from CDN\" but found \"\/\/Set cron job to update WPML config index file from CDN\"","source":"Squiz.Commenting.InlineComment.NoSpaceBefore","severity":5,"fixable":true,"type":"ERROR","line":147,"column":5},{"message":"Inline comments must end in full-stops, exclamation marks, or question marks","source":"Squiz.Commenting.InlineComment.InvalidEndChar","severity":5,"fixable":false,"type":"ERROR","line":147,"column":5},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":150,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":151,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":239,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":246,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":268,"column":5},{"message":"Found precision alignment of 3 spaces.","source":"WordPress.WhiteSpace.PrecisionAlignment.Found","severity":5,"fixable":false,"type":"WARNING","line":275,"column":1},{"message":"Tabs must be used to indent lines; spaces are not allowed","source":"Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed","severity":5,"fixable":true,"type":"ERROR","line":275,"column":1},{"message":"Inline comments must end in full-stops, exclamation marks, or question marks","source":"Squiz.Commenting.InlineComment.InvalidEndChar","severity":5,"fixable":false,"type":"ERROR","line":279,"column":1},{"message":"Variable \"WPML_Users_Languages_Dependencies\" is not in valid snake_case format","source":"WordPress.NamingConventions.ValidVariableName.NotSnakeCase","severity":5,"fixable":false,"type":"ERROR","line":284,"column":1},{"message":"Missing doc comment for function wpml_init_language_switcher()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":286,"column":1},{"message":"Missing doc comment for function wpml_mlo_init()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":293,"column":1},{"message":"Missing short description in doc comment","source":"Generic.Commenting.DocComment.MissingShort","severity":5,"fixable":false,"type":"ERROR","line":301,"column":1},{"message":"Missing parameter comment","source":"Squiz.Commenting.FunctionComment.MissingParamComment","severity":5,"fixable":false,"type":"ERROR","line":302,"column":4},{"message":"There must be exactly one blank line before the tags in a doc comment","source":"Generic.Commenting.DocComment.SpacingBeforeTags","severity":5,"fixable":true,"type":"ERROR","line":311,"column":8},{"message":"Found precision alignment of 1 spaces.","source":"WordPress.WhiteSpace.PrecisionAlignment.Found","severity":5,"fixable":false,"type":"WARNING","line":314,"column":1},{"message":"Tabs must be used to indent lines; spaces are not allowed","source":"Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed","severity":5,"fixable":true,"type":"ERROR","line":314,"column":1},{"message":"Found precision alignment of 1 spaces.","source":"WordPress.WhiteSpace.PrecisionAlignment.Found","severity":5,"fixable":false,"type":"WARNING","line":315,"column":1},{"message":"Tabs must be used to indent lines; spaces are not allowed","source":"Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed","severity":5,"fixable":true,"type":"ERROR","line":315,"column":1},{"message":"No space before closing parenthesis is prohibited","source":"WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceBeforeCloseParenthesis","severity":5,"fixable":true,"type":"ERROR","line":315,"column":67},{"message":"Missing doc comment for function wpml_integrations_requirements()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":334,"column":1},{"message":"Missing doc comment for function wpml_troubleshoot_action_load()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":341,"column":1},{"message":"Missing doc comment for function wpml_init_language_cookie_settings()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":352,"column":1},{"message":"Found precision alignment of 1 spaces.","source":"WordPress.WhiteSpace.PrecisionAlignment.Found","severity":5,"fixable":false,"type":"WARNING","line":358,"column":1},{"message":"Tabs must be used to indent lines; spaces are not allowed","source":"Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed","severity":5,"fixable":true,"type":"ERROR","line":358,"column":1},{"message":"Found precision alignment of 2 spaces.","source":"WordPress.WhiteSpace.PrecisionAlignment.Found","severity":5,"fixable":false,"type":"WARNING","line":359,"column":1},{"message":"Tabs must be used to indent lines; spaces are not allowed","source":"Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed","severity":5,"fixable":true,"type":"ERROR","line":359,"column":1},{"message":"Missing doc comment for function wpml_check_php_version()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":377,"column":1},{"message":"Comma not allowed after last value in single-line array declaration","source":"WordPress.Arrays.CommaAfterArrayItem.CommaAfterLast","severity":5,"fixable":true,"type":"ERROR","line":383,"column":52},{"message":"Missing doc comment for function wpml_core_loads_first()","source":"Squiz.Commenting.FunctionComment.Missing","severity":5,"fixable":false,"type":"ERROR","line":389,"column":1},{"message":"Variable assignment found within a condition. Did you mean to do a comparison?","source":"WordPress.CodeAnalysis.AssignmentInCondition.Found","severity":5,"fixable":false,"type":"WARNING","line":392,"column":27},{"message":"Assignments must be the first block of code on a line","source":"Squiz.PHP.DisallowMultipleAssignments.Found","severity":5,"fixable":false,"type":"ERROR","line":392,"column":27}]}}}$ cat ./phpcs.json
$ echo "Parsing results..."
Parsing results...
$ ./vendor/bin/diffFilter --phpcs files.txt ./phpcs.json 100
Can't Parse phpcs json - Syntax error
Job succeeded
```

I hope this is enough data to help me figure out what's wrong here.

**Comment by exussum12** [comment] 2019-03-15 14:41
Looks like there are 2 issues here

1 - Not being able to find the class
Are you using composer ? (by the look of the command you are ?) 

Can you post the result of the following
`grep -B 31 PhpParser composer.lock` 

and

`ls -R vendor/ |  grep nikic`


The second on gitlab, there looks to be a few issues
1 the first part should be diff.txt ie containing the lines which changed, files.txt just contains the lines which changed.
2. the phpcs.json doesnt seem to contain json. if you `cat phpcs.json` my guess is it will show some output from phpcs 


Hope that helps!

**Comment by andreasciamanna** [comment] 2019-03-15 15:04
@exussum12 Thanks for helping!

> Are you using composer ?

Yes I am.

Here's the result of `grep -B 31 PhpParser composer.lock`:
```
            "name": "nikic/php-parser",
            "version": "v3.1.5",
            "source": {
                "type": "git",
                "url": "https://github.com/nikic/PHP-Parser.git",
                "reference": "bb87e28e7d7b8d9a7fda231d37457c9210faf6ce"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/nikic/PHP-Parser/zipball/bb87e28e7d7b8d9a7fda231d37457c9210faf6ce",
                "reference": "bb87e28e7d7b8d9a7fda231d37457c9210faf6ce",
                "shasum": ""
            },
            "require": {
                "ext-tokenizer": "*",
                "php": ">=5.5"
            },
            "require-dev": {
                "phpunit/phpunit": "~4.0|~5.0"
            },
            "bin": [
                "bin/php-parse"
            ],
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "3.0-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "PhpParser\\": "lib/PhpParser"
```

And of `ls -R vendor/ | grep nikic`:
```
nikic
vendor//nikic:
vendor//nikic/php-parser:
vendor//nikic/php-parser/bin:
vendor//nikic/php-parser/doc:
vendor//nikic/php-parser/doc/component:
vendor//nikic/php-parser/grammar:
vendor//nikic/php-parser/lib:
vendor//nikic/php-parser/lib/PhpParser:
vendor//nikic/php-parser/lib/PhpParser/Builder:
vendor//nikic/php-parser/lib/PhpParser/Comment:
vendor//nikic/php-parser/lib/PhpParser/ErrorHandler:
vendor//nikic/php-parser/lib/PhpParser/Lexer:
vendor//nikic/php-parser/lib/PhpParser/Node:
vendor//nikic/php-parser/lib/PhpParser/Node/Expr:
vendor//nikic/php-parser/lib/PhpParser/Node/Expr/AssignOp:
vendor//nikic/php-parser/lib/PhpParser/Node/Expr/BinaryOp:
vendor//nikic/php-parser/lib/PhpParser/Node/Expr/Cast:
vendor//nikic/php-parser/lib/PhpParser/Node/Name:
vendor//nikic/php-parser/lib/PhpParser/Node/Scalar:
vendor//nikic/php-parser/lib/PhpParser/Node/Scalar/MagicConst:
vendor//nikic/php-parser/lib/PhpParser/Node/Stmt:
vendor//nikic/php-parser/lib/PhpParser/Node/Stmt/TraitUseAdaptation:
vendor//nikic/php-parser/lib/PhpParser/NodeVisitor:
vendor//nikic/php-parser/lib/PhpParser/Parser:
vendor//nikic/php-parser/lib/PhpParser/PrettyPrinter:
vendor//nikic/php-parser/lib/PhpParser/Serializer:
vendor//nikic/php-parser/lib/PhpParser/Unserializer:
vendor//nikic/php-parser/test:
vendor//nikic/php-parser/test/PhpParser:
vendor//nikic/php-parser/test/PhpParser/Builder:
vendor//nikic/php-parser/test/PhpParser/ErrorHandler:
vendor//nikic/php-parser/test/PhpParser/Lexer:
vendor//nikic/php-parser/test/PhpParser/Node:
vendor//nikic/php-parser/test/PhpParser/Node/Scalar:
vendor//nikic/php-parser/test/PhpParser/Node/Stmt:
vendor//nikic/php-parser/test/PhpParser/NodeVisitor:
vendor//nikic/php-parser/test/PhpParser/Parser:
vendor//nikic/php-parser/test/PhpParser/Serializer:
vendor//nikic/php-parser/test/PhpParser/Unserializer:
vendor//nikic/php-parser/test/code:
vendor//nikic/php-parser/test/code/parser:
vendor//nikic/php-parser/test/code/parser/errorHandling:
vendor//nikic/php-parser/test/code/parser/expr:
vendor//nikic/php-parser/test/code/parser/expr/fetchAndCall:
vendor//nikic/php-parser/test/code/parser/expr/uvs:
vendor//nikic/php-parser/test/code/parser/scalar:
vendor//nikic/php-parser/test/code/parser/stmt:
vendor//nikic/php-parser/test/code/parser/stmt/class:
vendor//nikic/php-parser/test/code/parser/stmt/function:
vendor//nikic/php-parser/test/code/parser/stmt/generator:
vendor//nikic/php-parser/test/code/parser/stmt/loop:
vendor//nikic/php-parser/test/code/parser/stmt/namespace:
vendor//nikic/php-parser/test/code/prettyPrinter:
vendor//nikic/php-parser/test/code/prettyPrinter/expr:
vendor//nikic/php-parser/test/code/prettyPrinter/stmt:
vendor//nikic/php-parser/test_old:
```

As for the problem in gitlab, my script was inspired from this wiki page: https://github.com/exussum12/coverageChecker/wiki/phpcs

I've only made the adjustments necessary to my needs.

The generated json is in the output I've pasted (you can see I actually did a `cat phpcs.json` there) and, as far as I can see, it's a valid one.

You can see a prettified version here: https://gist.github.com/andreasciamanna/08288b992c77c401d484bffadf7ec7c9

**Comment by exussum12** [comment] 2019-03-16 18:17
Which os are you running locally ?

**Comment by andreasciamanna** [comment] 2019-03-17 08:06
MacOS

**Comment by exussum12** [comment] 2019-03-17 21:06
can you update to use dev-debugging and run that. there is some debugging for both issues there.

**Comment by andreasciamanna** [comment] 2019-03-18 08:04
Thanks, @exussum12.

I think your repo is not updating Packagist automatically because Composer can't see this branch.
In fact, the dev-branch I can see in Packagist is `dev-fileNotFound`:
![image](https://user-images.githubusercontent.com/181780/54515494-81805180-495c-11e9-8596-8b346423ac2b.png)


Anyway, I've added the GitHub repo in the repositories branches and I was able to switch to "dev-debugging", but the problem is still present, with an extra initial message about autoloader:

```
Using auto loader .../vendor/exussum12/coverage-checker/src/../autoload.phpPHP Fatal error:  Class 'PhpParser\ParserFactory' not found in .../vendor/exussum12/coverage-checker/src/FileParser.php on line 21
PHP Stack trace:
PHP   1. {main}() .../vendor/exussum12/coverage-checker/bin/diffFilter:0
PHP   2. require() .../vendor/exussum12/coverage-checker/bin/diffFilter:3
PHP   3. exussum12\CoverageChecker\CoverageCheck->getCoveredLines() .../vendor/exussum12/coverage-checker/src/Runners/generic.php:76
PHP   4. exussum12\CoverageChecker\PhpCsLoader->parseLines() .../vendor/exussum12/coverage-checker/src/CoverageCheck.php:72
PHP   5. exussum12\CoverageChecker\PhpCsLoader->addInvalidLine() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:88
PHP   6. exussum12\CoverageChecker\PhpCsLoader->handleLookupError() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:131
PHP   7. exussum12\CoverageChecker\PhpCsLoader->getFileParser() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:167
PHP   8. exussum12\CoverageChecker\FileParser->__construct() .../vendor/exussum12/coverage-checker/src/PhpCsLoader.php:185
```

**Comment by exussum12** [comment] 2019-03-18 10:19
brilliant thanks, I have reproduced the issue and will issue a fix ASAP

**Comment by exussum12** [comment] 2019-03-18 18:52
0.11.1 has been released to fix this. Can you also send the output when running on gitlab ?

**Comment by exussum12** [comment] 2019-03-27 20:42
Are you still getting the error on gitlab ?

**Comment by andreasciamanna** [comment] 2019-03-28 10:04
@exussum12 I'm a bit stuck with other tasks at the moment.

I had to put this one on hold.

I'm planning to get back to it in one or two weeks from now.

**Comment by exussum12** [comment] 2019-08-10 08:53
Closing for now. If you get time again please re open. Would be glad to help

**Closed as completed by exussum12** 2019-08-10 08:53 UTC
